app:
  search:
    pagination:
      numberRecords:
        default: 10
        max: 100

spring:
  application.name: exemplo-kotlin-springboot-rest
  h2.console:
    enabled: true
    path: /h2-console
  jpa.hibernate.ddl-auto: validate
  messages:
    fallback-to-system-locale: true
    use-code-as-default-message: true
    basename: messages, validation-messages

# Configuração de log.
logging:
  level:
    org:
      apache.http: INFO
      springframework: INFO
      spring: INFO
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
    com:
      andrejusti: INFO
      andrejusti.example.kotlin.springboot.rest.exception.ValidationException: OFF